### ISSUE TITLE
JavaScript/NodeJS: Fix `MaxListenersExceededWarning` issue

### ISSUE THREAD

**Issue by inoas** [inoas/glacier#4]
```shell
(node:35633) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at process.addListener (node:events:605:10)
    at os_command (file:///Users/USERNAME/local-dev/contrib/gleam/glacier/build/dev/javascript/shellout/shellout_ffi.mjs:77:13)
    at file:///Users/USERNAME/local-dev/contrib/gleam/glacier/build/dev/javascript/shellout/shellout.mjs:300:12
    at Module.command (file:///Users/USERNAME/local-dev/contrib/gleam/glacier/build/dev/javascript/shellout/shellout.mjs:301:5)
    at run_tests (file:///Users/USERNAME/local-dev/contrib/gleam/glacier/build/dev/javascript/glacier/glacier.mjs:185:23)
    at file:///Users/USERNAME/local-dev/contrib/gleam/glacier/build/dev/javascript/glacier/glacier.mjs:77:29
    at Timeout._onTimeout (file:///Users/USERNAME/local-dev/
```

**Comment by inoas** [comment]
Note: Glacier runs despite this bug, the warning is only emitted once and taking a look at system resources did not show for memory to increase continously after a few tests but only initially rising to around 60MiB.

**Comment by inoas** [comment]
Target NodeJS 18 LTS

**Comment by inoas** [comment]
Fixed in this commit <https://github.com/inoas/glacier/commit/d0bcde35f5a5e059172b2dc70ed46d4d1683371a#diff-ecf2ea93be79ae7a2f3e8a99901462f8be63f144a3338a8e013541d3c801ac9fL124-L125>
